language: node_js
sudo: false
node_js:
- '8'
- '9'
- '10'
- '12'
- '13'
- '14'
branches:
  except:
    - /^v[0-9]/
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install -g yarn --cache-min 999999999
install:
  - yarn
